Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Loop over each entry and collect the dataframe
df = []
for entry in meta:
    if entry['category'] == 'T1mapping':
        fpath, fname, category, method, author = entry.values()
        df_entry = pd.read_csv(Path(fpath, fname)).assign(method=method, author=author)
        df.append(df_entry)
    
# Concat all entries
df = pd.concat(df)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# Loop over each entry and collect the dataframe[39;00m
[1;32m      2[0m df [38;5;241m=[39m []
[0;32m----> 3[0m [38;5;28;01mfor[39;00m entry [38;5;129;01min[39;00m [43mmeta[49m:
[1;32m      4[0m     [38;5;28;01mif[39;00m entry[[38;5;124m'[39m[38;5;124mcategory[39m[38;5;124m'[39m] [38;5;241m==[39m [38;5;124m'[39m[38;5;124mT1mapping[39m[38;5;124m'[39m:
[1;32m      5[0m         fpath, fname, category, method, author [38;5;241m=[39m entry[38;5;241m.[39mvalues()

[0;31mNameError[0m: name 'meta' is not defined
NameError: name 'meta' is not defined

